/* Generated By:JavaCC: Do not edit this line. LocParserConstants.java */
package com.github.lindenb.vizbam.locparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LocParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMA = 3;
  /** RegularExpression Id. */
  int LETTER = 4;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int BP = 7;
  /** RegularExpression Id. */
  int KB = 8;
  /** RegularExpression Id. */
  int MB = 9;
  /** RegularExpression Id. */
  int GB = 10;
  /** RegularExpression Id. */
  int IDENTIFIER = 11;
  /** RegularExpression Id. */
  int COLON = 12;
  /** RegularExpression Id. */
  int DASH = 13;
  /** RegularExpression Id. */
  int PLUS = 14;
  /** RegularExpression Id. */
  int DELIM = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\",\"",
    "<LETTER>",
    "<DIGIT>",
    "<INT>",
    "<BP>",
    "<KB>",
    "<MB>",
    "<GB>",
    "<IDENTIFIER>",
    "\":\"",
    "\"-\"",
    "\"+\"",
    "<DELIM>",
  };

}
